export interface Plan {
  id: string;
  name: string;
  price: number;
  image: string;
  features: string[];
  supportDuration?: string;
}

export const plansSpanish : Plan[] = [
  {
    id: "pinnacle",
    name: "Pinnacle",
    price: 82620,
    image: "https://ext.same-assets.com/608674375/472844883.jpeg",
    features: [
      "Desarrollo de sistemas complejos: Integración completa con sistemas heredados y soluciones a medida.",
      "Desarrollo de aplicaciones móviles y web: Con diseño UX/UI de alta fidelidad y funcionalidades avanzadas.",
      "Migración y actualización de sistemas: Servicios completos para actualizar sistemas existentes.",
      "Consultoría y auditoría: Evaluación exhaustiva y recomendaciones para optimización.",
      "Soporte técnico y mantenimiento: Por 24 meses con capacitación para el personal.",
    ],
  },
  {
    id: "transform",
    name: "Transform",
    price: 68250,
    image: "https://ext.same-assets.com/608674375/2602680073.jpeg",
    features: [
      "Desarrollo de una aplicación empresarial personalizada: Con integración de bases de datos y seguridad avanzada.",
      "Desarrollo de una página web: Hasta 30 secciones con diseño UX/UI de alta gama.",
      "Integración de sistemas: Con sistemas heredados y API personalizadas.",
      "Marketing digital: Estrategia integral con campañas avanzadas y optimización de conversión.",
      "Soporte técnico: Por 24 meses.",
    ],
  },
  {
    id: "innovate",
    name: "Innovate",
    price: 55000,
    image: "https://ext.same-assets.com/608674375/3841572836.jpeg",
    features: [
      "Desarrollo de software a medida: Con integración de APIs y características personalizadas.",
      "Desarrollo de aplicaciones móviles: Para Android e iOS con funcionalidades avanzadas.",
      "Diseño y desarrollo web: Hasta 20 secciones con diseño gráfico avanzado.",
      "Consultoría y auditoría: Asesoría para la mejora de procesos y software.",
      "Soporte técnico: Por 18 meses.",
    ],
  },
  {
    id: "advance",
    name: "Advance",
    price: 48500,
    image: "https://ext.same-assets.com/608674375/924027943.jpeg",
    features: [
      "Desarrollo de una tienda en línea: Con hasta 50 productos, integración de pasarela de pago y funciones avanzadas de e-commerce.",
      "Desarrollo de aplicación móvil: Funciones avanzadas con diseño UX/UI mejorado.",
      "SEO avanzado: Estrategias de optimización para mejorar la visibilidad en motores de búsqueda.",
      "Marketing digital: Incluye campañas en redes sociales y Google Ads.",
      "Soporte técnico: Por 12 meses.",
    ],
  },
  {
    id: "optimize",
    name: "Optimize",
    price: 42000,
    image: "https://ext.same-assets.com/608674375/2555595820.jpeg",
    features: [
      "Desarrollo de página web: Hasta 15 páginas con diseño gráfico personalizado y funciones interactivas.",
      "Desarrollo de aplicación móvil: Con integración de funcionalidades adicionales como notificaciones push.",
      "Integración de CMS: Sistema de gestión de contenido avanzado.",
      "SEO y marketing digital: Estrategia avanzada con informes mensuales y campañas específicas.",
      "Soporte técnico: Por 9 meses.",
    ],
  },
  {
    id: "accelerate",
    name: "Accelerate",
    price: 36800,
    image: "https://ext.same-assets.com/608674375/1238972269.jpeg",
    features: [
      "Desarrollo de una página web: Hasta 10 páginas con diseño responsivo y optimización para dispositivos móviles.",
      "Integración de redes sociales: Avanzada con botones de compartir, feeds en vivo y opciones de interacción.",
      "Desarrollo de aplicación móvil: Funcionalidad básica para Android o iOS.",
      "SEO avanzado: Implementación de técnicas de SEO on-page y off-page.",
      "Soporte técnico: Por 6 meses.",
    ],
  },
  {
    id: "empower",
    name: "Empower",
    price: 26245,
    image: "https://ext.same-assets.com/608674375/4124700561.jpeg",
    features: [
      "Desarrollo integral de sistemas complejos",
      "Integración con sistemas heredados",
      "Diseño UX/UI de alta fidelidad",
      "Servicios de migración y actualización de sistemas",
      "Soporte técnico y mantenimiento por 24 meses",
      "Servicios de capacitación para el personal",
    ],
  },
  {
    id: "expand",
    name: "Expand",
    price: 20000,
    image: "https://ext.same-assets.com/608674375/3088857897.jpeg",
    features: [
      "Desarrollo de software a medida",
      "Integración de APIs",
      "Diseño y desarrollo de aplicaciones web y móviles",
      "Consultoría y auditoría de software",
      "Soporte técnico y mantenimiento por 18 meses",
    ],
  },
  {
    id: "elevate",
    name: "Elevate",
    price: 15750,
    image: "https://ext.same-assets.com/608674375/4093096630.jpeg",
    features: [
      "Desarrollo de una aplicación empresarial personalizada",
      "Integración de bases de datos",
      "Diseño UX/UI avanzado",
      "Implementación de seguridad avanzada",
      "Soporte técnico por 12 meses",
    ],
  },
  {
    id: "boost-2",
    name: "Boost 2.0",
    price: 12500,
    image: "https://ext.same-assets.com/608674375/2820496772.jpeg",
    features: [
      "Desarrollo de una tienda en línea (e-commerce)",
      "Integración de pasarela de pago",
      "Diseño gráfico personalizado",
      "SEO y marketing digital básico",
      "Soporte técnico por 9 meses",
    ],
  },
  {
    id: "assist",
    name: "Assist",
    price: 8750,
    image: "https://ext.same-assets.com/608674375/1908606859.jpeg",
    features: [
      "Desarrollo de aplicaciones móviles (Android e iOS)",
      "Diseño y desarrollo web avanzado",
      "Integración de sistema de gestión de contenido (CMS)",
      "SEO avanzado",
      "Soporte técnico por 6 meses",
    ],
  },
  {
    id: "nexa",
    name: "Nexa",
    price: 7154,
    image: "https://ext.same-assets.com/608674375/747611334.jpeg",
    features: [
      "Desarrollo de una web con hasta 7 páginas",
      "Diseño gráfico básico",
      "Implementación de formularios de contacto",
      "SEO básico",
      "Soporte técnico por 4 meses",
    ],
  },
  {
    id: "create",
    name: "Create",
    price: 5500,
    image: "https://ext.same-assets.com/608674375/832932170.jpeg",
    features: [
      "Desarrollo de una web con hasta 5 páginas",
      "Diseño gráfico básico",
      "Implementación de formularios de contacto",
      "SEO básico",
      "Soporte técnico por 3 meses",
    ],
  },
  {
    id: "development",
    name: "Development",
    price: 3500,
    image: "https://ext.same-assets.com/608674375/3741705283.jpeg",
    features: [
      "Desarrollo de una aplicación móvil sencilla",
      "Diseño y desarrollo web básico",
      "Mantenimiento y soporte de software",
      "Hasta 3 revisiones de diseño",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: 1360,
    image: "https://ext.same-assets.com/608674375/3606627329.jpeg",
    features: [
      "Desarrollo de una página web simple (HTML, CSS)",
      "Diseño responsivo",
      "Integración básica de redes sociales",
      "Soporte técnico básico por 1 mes",
    ],
  },
  {
    id: "boost",
    name: "Boost",
    price: 680,
    image: "https://ext.same-assets.com/608674375/3606627329.jpeg",
    features: [
      "Soporte técnico limitado por 2 semanas, solo vía correo electrónico.",
      "1 revisión menor del diseño que ya exista.",
    ],
  },
  {
    id: "ignite",
    name: "Ignite",
    price: 344,
    image: "https://ext.same-assets.com/608674375/822494986.jpeg",
    features: [
      "Soporte técnico limitado por 1 semana solo vía correo electrónico.",
    ],
  },
  {
    id: "launch",
    name: "Launch",
    price: 205,
    image: "https://ext.same-assets.com/608674375/3804215284.jpeg",
    features: [
      "Soporte técnico limitado por 5 días solo vía correo electrónico.",
    ],
  },
  {
    id: "spark",
    name: "Spark",
    price: 157,
    image: "https://ext.same-assets.com/608674375/665403416.jpeg",
    features: [
      "Soporte técnico limitado por 3 días solo vía correo electrónico.",
    ],
  },
];


export const plansEnglish: Plan[] = [
  {
    id: "pinnacle",
    name: "Pinnacle",
    price: 82620,
    image: "https://ext.same-assets.com/608674375/472844883.jpeg",
    features: [
      "Complex systems development: Full integration with legacy systems and custom solutions.",
      "Mobile and web application development: With high-fidelity UX/UI design and advanced functionality.",
      "System migration and upgrades: Comprehensive services to update existing systems.",
      "Consulting and auditing: Thorough assessment and recommendations for optimization.",
      "Technical support and maintenance: For 24 months with staff training.",
    ],
  },
  {
    id: "transform",
    name: "Transform",
    price: 68250,
    image: "https://ext.same-assets.com/608674375/2602680073.jpeg",
    features: [
      "Custom business application development: With database integration and advanced security.",
      "Website development: Up to 30 sections with high-end UX/UI design.",
      "Systems integration: With legacy systems and custom APIs.",
      "Digital marketing: Comprehensive strategy with advanced campaigns and conversion optimization.",
      "Technical support: For 24 months.",
    ],
  },
  {
    id: "innovate",
    name: "Innovate",
    price: 55000,
    image: "https://ext.same-assets.com/608674375/3841572836.jpeg",
    features: [
      "Custom software development: With API integration and custom features.",
      "Mobile app development: For Android and iOS with advanced functionality.",
      "Web design and development: Up to 20 sections with advanced graphic design.",
      "Consulting and auditing: Advisory services to improve processes and software.",
      "Technical support: For 18 months.",
    ],
  },
  {
    id: "advance",
    name: "Advance",
    price: 48500,
    image: "https://ext.same-assets.com/608674375/924027943.jpeg",
    features: [
      "Online store development: With up to 50 products, payment gateway integration, and advanced e-commerce features.",
      "Mobile app development: Advanced features with improved UX/UI design.",
      "Advanced SEO: Optimization strategies to improve search engine visibility.",
      "Digital marketing: Includes social media campaigns and Google Ads.",
      "Technical support: For 12 months.",
    ],
  },
  {
    id: "optimize",
    name: "Optimize",
    price: 42000,
    image: "https://ext.same-assets.com/608674375/2555595820.jpeg",
    features: [
      "Website development: Up to 15 pages with custom graphic design and interactive features.",
      "Mobile app development: With integration of additional features such as push notifications.",
      "CMS integration: Advanced content management system.",
      "SEO and digital marketing: Advanced strategy with monthly reports and targeted campaigns.",
      "Technical support: For 9 months.",
    ],
  },
  {
    id: "accelerate",
    name: "Accelerate",
    price: 36800,
    image: "https://ext.same-assets.com/608674375/1238972269.jpeg",
    features: [
      "Website development: Up to 10 pages with responsive design and mobile optimization.",
      "Social media integration: Advanced with share buttons, live feeds, and interaction options.",
      "Mobile app development: Basic functionality for Android or iOS.",
      "Advanced SEO: Implementation of on-page and off-page SEO techniques.",
      "Technical support: For 6 months.",
    ],
  },
  {
    id: "empower",
    name: "Empower",
    price: 26245,
    image: "https://ext.same-assets.com/608674375/4124700561.jpeg",
    features: [
      "Comprehensive development of complex systems",
      "Integration with legacy systems",
      "High-fidelity UX/UI design",
      "System migration and upgrade services",
      "Technical support and maintenance for 24 months",
      "Staff training services",
    ],
  },
  {
    id: "expand",
    name: "Expand",
    price: 20000,
    image: "https://ext.same-assets.com/608674375/3088857897.jpeg",
    features: [
      "Custom software development",
      "API integration",
      "Web and mobile application design and development",
      "Software consulting and auditing",
      "Technical support and maintenance for 18 months",
    ],
  },
  {
    id: "elevate",
    name: "Elevate",
    price: 15750,
    image: "https://ext.same-assets.com/608674375/4093096630.jpeg",
    features: [
      "Custom business application development",
      "Database integration",
      "Advanced UX/UI design",
      "Advanced security implementation",
      "Technical support for 12 months",
    ],
  },
  {
    id: "boost-2",
    name: "Boost 2.0",
    price: 12500,
    image: "https://ext.same-assets.com/608674375/2820496772.jpeg",
    features: [
      "Online store development (e-commerce)",
      "Payment gateway integration",
      "Custom graphic design",
      "Basic SEO and digital marketing",
      "Technical support for 9 months",
    ],
  },
  {
    id: "assist",
    name: "Assist",
    price: 8750,
    image: "https://ext.same-assets.com/608674375/1908606859.jpeg",
    features: [
      "Mobile app development (Android and iOS)",
      "Advanced web design and development",
      "Content management system (CMS) integration",
      "Advanced SEO",
      "Technical support for 6 months",
    ],
  },
  {
    id: "nexa",
    name: "Nexa",
    price: 7154,
    image: "https://ext.same-assets.com/608674375/747611334.jpeg",
    features: [
      "Website development with up to 7 pages",
      "Basic graphic design",
      "Contact form implementation",
      "Basic SEO",
      "Technical support for 4 months",
    ],
  },
  {
    id: "create",
    name: "Create",
    price: 5500,
    image: "https://ext.same-assets.com/608674375/832932170.jpeg",
    features: [
      "Website development with up to 5 pages",
      "Basic graphic design",
      "Contact form implementation",
      "Basic SEO",
      "Technical support for 3 months",
    ],
  },
  {
    id: "development",
    name: "Development",
    price: 3500,
    image: "https://ext.same-assets.com/608674375/3741705283.jpeg",
    features: [
      "Simple mobile application development",
      "Basic web design and development",
      "Software maintenance and support",
      "Up to 3 design revisions",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: 1360,
    image: "https://ext.same-assets.com/608674375/3606627329.jpeg",
    features: [
      "Simple website development (HTML, CSS)",
      "Responsive design",
      "Basic social media integration",
      "Basic technical support for 1 month",
    ],
  },
  {
    id: "boost",
    name: "Boost",
    price: 680,
    image: "https://ext.same-assets.com/608674375/3606627329.jpeg",
    features: [
      "Limited technical support for 2 weeks, email only.",
      "1 minor revision of an existing design.",
    ],
  },
  {
    id: "ignite",
    name: "Ignite",
    price: 344,
    image: "https://ext.same-assets.com/608674375/822494986.jpeg",
    features: [
      "Limited technical support for 1 week, email only.",
    ],
  },
  {
    id: "launch",
    name: "Launch",
    price: 205,
    image: "https://ext.same-assets.com/608674375/3804215284.jpeg",
    features: [
      "Limited technical support for 5 days, email only.",
    ],
  },
  {
    id: "spark",
    name: "Spark",
    price: 157,
    image: "https://ext.same-assets.com/608674375/665403416.jpeg",
    features: [
      "Limited technical support for 3 days, email only.",
    ],
  },
];